[package]
name = "atakit-workload"
version.workspace = true
edition.workspace = true

[features]
cli = ["clap"]

[dependencies]
atakit-core.workspace = true
atakit-github.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
sha2.workspace = true
hex.workspace = true
tar.workspace = true
flate2.workspace = true
zstd.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
futures-util.workspace = true
chrono.workspace = true

tempfile.workspace = true

clap = { workspace = true, optional = true }

[dev-dependencies]
