[package]
name = "atakit-verifierd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atakit-attestation.workspace = true
atakit-attestation-client.workspace = true
atakit-cvm-encoding.workspace = true
atakit-cvm-types.workspace = true
async-trait.workspace = true
axum.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
k256.workspace = true
tempfile.workspace = true
tower = "0.5"
